# Project Information
site_name: ICS Wiki
site_description: ICS Wiki 是 NJU 信息与计算科学（羟基）专业的站点
site_author: NJU

repo_name: 'Birdium/ics-wiki'
repo_url: 'https://github.com/Birdium/ics-wiki/'
edit_uri: 'edit/main/docs'

theme:
  name: material
  language: 'zh'

# Contents
nav:
  - 简介: index.md
  - 课程:
    - 大一上:
      - 数学分析: Course/MathAnalysis1.md
      - 高等代数: Course/LinAlg.md
      - 信息与计算科学导论: Course/icsIntro.md
      - 信息与计算科学实验: Course/icsIntroLab.md
    - 大一下:
      - 数学分析: Course/MathAnalysis2.md
      - 高等代数: Course/LinAlg2.md
      - 离散数学: Course/DiscreteMath.md
      - 信息科学与实践: Course/LAOZHAO1.md
      - 大学物理: Course/Physics.md
    - 大二上: 
      - 密码学原理: Course/Crypto.md
      - 概率论与数理统计: Course/Probabilitics.md
      - 数据结构: Course/DataStructure.md
      - 近世代数: Course/AbstractAlgebra.md
      - 凸优化: Course/ConvexOptimization.md
    - 大二下:
      - 算法设计与分析: Course/Algorithm.md
      - 图论与算法: Course/Graph.md
      - 数理逻辑: Course/MathLogic.md 
      - 计算方法: Course/Numerical.md 
      - 博弈论及其应用: Course/GameTheory.md
    # - 大三上: 
  - OJ:
    - test: test.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
